### ISSUE TITLE
unzip: can't open /opt/ProfitTrailer-2.4.52.zip - container restarting

### ISSUE THREAD

**Issue by dodancs** [rafffael/profit-trailer#12]
Hey.

I don't exactly know, how this happened, but here is the log:
```
unzip: can't open /opt/ProfitTrailer-2.4.52.zip[.zip]
Error: no ProfitTrailer jar found. Exiting.
/run-profit-trailer.sh: exit: line 16: Illegal number: -1
```

Now, when I created a new container, with an empty volume connected to /app, the container still spits out this error. I think your Dockerfile is broken in some way.

Maybe consider adding a check for the JAR file, and if it does not exist, download it again from the PT_DL url?

**Comment by rafffael** [comment]
Hi,

I have not pushed the v2.4.52 yet, but it should work if you modify the Dockerfile PT_VERSION anyway.
I cannot reproduce this error locally.

here is my output log with PT_VERSION=2.4.52 :
```
mybot_1  | No properties found, extracting...
mybot_1  | Archive:  /opt/ProfitTrailer-2.4.52.zip
mybot_1  |   inflating: linux-update.sh
mybot_1  |   inflating: pm2-ProfitTrailer.json
mybot_1  |   inflating: ProfitTrailer.jar
mybot_1  |   inflating: Run-ProfitTrailer.cmd
mybot_1  | 2021-02-16 21:26:09 INFO Application - PT INFO - Version: 2.4.52 -- Port: 8081 -- Path: /
mybot_1  | 2021-02-16 21:26:09 INFO Application - Java Version: 1.8.0_212
mybot_1  | 2021-02-16 21:26:10 INFO Application - Please finish the setup process in your browser
```
