### ISSUE TITLE
Please start the bot using the provided cmd or json file or at least provide an -Xmx value

### ISSUE THREAD

**Issue by maah75** [rafffael/profit-trailer#2]
Hi 

I love your work and this container the only reason to get back to Profit Trailer. I had this working for a wile now but with the new V 2.3.0 stop working and I get this message any idea how to fix it 

Please start the bot using the provided cmd or json file or at least provide an -Xmx value

Thanks

my setup Synology Ds1515+

**Comment by rafffael** [comment]
Hi maah75,
I ran through the config and fixed your issue by adding the missing arguments to the java cmd.
Please let me know if this solution works for your NAS.

**Comment by maah75** [comment]
working fine as it should be ^_^ Thanks
