### ISSUE TITLE
Getting an error from the docker log for the new image

### ISSUE THREAD

**Issue by raenrfm** [rafffael/profit-trailer#6]
docker logs keen_ritchie
unzip:  cannot find or open /opt/ProfitTrailer-2.3.7.zip, /opt/ProfitTrailer-2.3.7.zip.zip or /opt/ProfitTrailer-2.3.7.zip.ZIP.
Error: no ProfitTrailer jar found. Exiting.
Error: no ProfitTrailer jar found. Exiting.
unzip:  cannot find or open /opt/ProfitTrailer-2.3.7.zip, /opt/ProfitTrailer-2.3.7.zip.zip or /opt/ProfitTrailer-2.3.7.zip.ZIP.
Error: no ProfitTrailer jar found. Exiting.

Something missing inside it?  I pulled the new image.

**Comment by rafffael** [comment]
indeed, there was an issue with the dockerfile
I just fixed it, please pull the latest image
