### ISSUE TITLE
Running 2 PT containers

### ISSUE THREAD

**Issue by raenrfm** [rafffael/profit-trailer#7]
I'm having a problem running a second container.  I created a separate directory for the new bot, used a different external port and kept everything the same.  It seems to not let me past the initial setup screen where you can choose public templates etc and kicks me back to the login screen.  Any idea why that might be?

**Comment by rafffael** [comment]
Do you use docker-compose?
You have to redirect your external port to the container port 8081

**Comment by raenrfm** [comment]
yes I redirected the internal 8081 to 8082 on the host so that should be
fine correct?  Just with the docker run command.

**Comment by raenrfm** [comment]
It's just weird, the new container should be referencing the new directory
with the separate config files so I'm not sure what's going on.

**Comment by raenrfm** [comment]
Ah nvm, I figured it out....it was a chrome issue, I was able to get past
the initial setup on a different machine so it was probably something
cookie or cache related.
