### ISSUE TITLE
How use/setup 2.4.3?

### ISSUE THREAD

**Issue by mikkelnl** [rafffael/profit-trailer#8]
Hi!

Trying to run a container on Synology, seems to start but immediately says:

Done! Now, edit your configuration files and reload the container.

I see some files in the assigned volume folder, but I believe 2.4.3 doesn't use configuration files anymore and it runs a setup wizard, right? So I'm not sure how to get the container running, cause it shuts down after te above message...?

**Comment by rafffael** [comment]
Hello,
Indeed, since 2.4.0 the config is done directly in your web browser on port 8081.
I just fixed this issue, please try this :
`docker run -d --name profittrailer rafffael/profit-trailer:2.4.3`

**Comment by rafffael** [comment]
I forgot to expose port 8081:
`docker run -d --name profittrailer -p 8081:8081 rafffael/profit-trailer:2.4.3`
